"""make email unique

Revision ID: bdccbc22949d
Revises: ec9b141ef5aa
Create Date: 2024-10-18 20:23:00.531665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bdccbc22949d'
down_revision: Union[str, None] = 'ec9b141ef5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_member_email', table_name='member')
    op.create_index(op.f('ix_member_email'), 'member', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_member_email'), table_name='member')
    op.create_index('ix_member_email', 'member', ['email'], unique=False)
    # ### end Alembic commands ###
