"""more models

Revision ID: fbb1a092f94c
Revises: bdccbc22949d
Create Date: 2024-10-18 21:36:25.885499

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "fbb1a092f94c"
down_revision: Union[str, None] = "bdccbc22949d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookloans",
        sa.Column("book_id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.Integer(), nullable=False),
        sa.Column("loan_date", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bookloans_book_id"), "bookloans", ["book_id"], unique=False
    )
    op.create_index(op.f("ix_bookloans_id"), "bookloans", ["id"], unique=False)
    op.create_index(
        op.f("ix_bookloans_member_id"), "bookloans", ["member_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bookloans_member_id"), table_name="bookloans")
    op.drop_index(op.f("ix_bookloans_id"), table_name="bookloans")
    op.drop_index(op.f("ix_bookloans_book_id"), table_name="bookloans")
    op.drop_table("bookloans")
    # ### end Alembic commands ###
